name: Dev/Firebase Hosting Deployment

on:
  push:
    branches: 
      - dev
    paths:
      - 'firebase-backend/hosting/**'
      - '.github/workflows/dev firebase deploy.yml'

  pull_request:
    branches: 
      - dev
    paths:
      - 'firebase-backend/hosting/**'
      - '.github/workflows/dev firebase deploy.yml'

  workflow_dispatch:

jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Firebase Hosting Deploy Dev
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_THE_BUTLER_X }}"
          projectId: the-butler-x
          channelId: dev
          entryPoint: 'firebase-backend/'
