name: CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

  workflow_dispatch:

jobs:
  deploy_backend_heroku:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Heroku
      - uses: actions/checkout@v2
      - uses: AkhileshNS/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_email: ammarrmalik185@hotmail.com
          heroku_app_name: the-butler-x
          buildpack: heroku/nodejs
          appdir: 'node-backend/'

  deploy_frontend_firebase:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy To Firebase Hosting
      - uses: actions/checkout@v2
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_THE_BUTLER_X }}"
          projectId: the-butler-x
          channelId: dev
          entryPoint: 'firebase-backend/'
