name: CI

on:
  push:
    branches: 
      - master
      - dev
  pull_request:
    branches: 
      - master
      - dev

  workflow_dispatch:

jobs:
  setup_environment_variables:
      runs-on: ubuntu-latest
      steps:
        - name: Get branch name (merge)
          if: github.event_name != 'pull_request'
          shell: bash
          run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | tr / -)" >> $GITHUB_ENV

        - name: Get branch name (pull request)
          if: github.event_name == 'pull_request'
          shell: bash
          run: echo "BRANCH_NAME=$(echo ${GITHUB_HEAD_REF} | tr / -)" >> $GITHUB_ENV

        - name: Debug
          run: echo ${{ env.BRANCH_NAME }}

  deploy_backend_heroku:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Deploy Backend To Heroku Live
        if: ${{ env.BRANCH_NAME }} == 'master'
        uses: AkhileshNS/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_email: ammarrmalik185@hotmail.com
          heroku_app_name: the-butler-x
          buildpack: heroku/nodejs
          appdir: 'node-backend/'

      - name: Deploy Backend To Heroku Dev
        if: ${{ env.BRANCH_NAME }} == 'dev'
        uses: AkhileshNS/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_email: ammarrmalik185@hotmail.com
          heroku_app_name: the-butler-x-dev
          buildpack: heroku/nodejs
          appdir: 'node-backend/'


  deploy_frontend_firebase:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Firebase Hosting Deploy Live
        uses: FirebaseExtended/action-hosting-deploy@v0
        if: ${{ env.BRANCH_NAME }} == 'master'
        with:
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_THE_BUTLER_X }}"
          projectId: the-butler-x
          channelId: live
          entryPoint: 'firebase-backend/'

      - name: Firebase Hosting Deploy Live
        uses: FirebaseExtended/action-hosting-deploy@v0
        if: ${{ env.BRANCH_NAME }} == 'dev'
        with:
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_THE_BUTLER_X }}"
          projectId: the-butler-x
          channelId: dev
          entryPoint: 'firebase-backend/'
